### ISSUE TITLE
Hi, is there a way the translation maintains the breaks

### ISSUE THREAD

**Issue by nam-co** [Kakadua/Translate-in-PHP#1]
Hi, Thanks for the cool work, I was wondering if theres a way of the script to translate and maintain white spaces and breaks instead of outputting everything in one sentence?

appreciate any help

**Comment by popeen** [comment]
Glad you like it.
Yeah, I think that would be possible. I will look into it.

**Comment by popeen** [comment]
What is the string you are having problem with?
Did some testing and linebreaks (\n) seems to already work. Same with whitespace.
